DROP DATABASE IF EXISTS photos;
CREATE DATABASE photos CHARSET utf8mb4;
USE photos;
 
CREATE TABLE fotos(
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(25) NOT NULL,
    url VARCHAR(255) NOT NULL,
    fecha DATE NOT NULL,
    descripcion VARCHAR(2048) NOT NULL
);